log_level = "warn"
position = "Top"

[modules]
left = [ [ "Workspaces" ] ]
center = [ "WindowTitle" ]
right = [ "SystemInfo", ["Clock", "media_player", "Privacy", "Settings", "Tray" ] ]

[workspaces]
enable_workspace_filling = true

[window_title]
truncate_title_after_length = 100

[system_info]
indicators = ["Cpu", "Memory", "Temperature", "UploadSpeed", "DownloadSpeed"]

[system_info.temperature]
sensor = "amdgpu edge"

[settings]
# Power Commands
shutdown_cmd = "systemctl poweroff"
reboot_cmd   = "systemctl reboot"
suspend_cmd  = "systemctl suspend"
hibernate_cmd = "systemctl hibernate"

# Session Commands (for Hyprland)
lock_cmd     = "hyprlock"
logout_cmd   = "hyprctl dispatch exit"
audio_sinks_more_cmd = "pavucontrol -t 3"
audio_sources_more_cmd = "pavucontrol -t 4"
wifi_more_cmd = "nm-connection-editor"
vpn_more_cmd = "nm-connection-editor"
bluetooth_more_cmd = "blueberry"

[appearance]
style = "Islands"
primary_color = "#7aa2f7"
success_color = "#9ece6a"
text_color = "#a9b1d6"
workspace_colors = [ "#7aa2f7", "#9ece6a" ]
special_workspace_colors = [ "#7aa2f7", "#9ece6a" ]

[appearance.danger_color]
base = "#f7768e"
weak = "#e0af68"

[appearance.background_color]
base = "#1a1b26"
weak = "#24273a"
strong = "#414868"

[appearance.secondary_color]
base = "#0c0d14"